taskkill /f /im wscript.exe
taskkill /f /im skeincpu64.exe
taskkill /f /im skeingpu.exe
taskkill /f /im skeincpu32.exe
taskkill /f /im scryptcpu64.exe
taskkill /f /im scryptcpu32.exe
taskkill /f /im scryptgpu.exe
taskkill /f /im scryptnvgpu.exe
taskkill /f /im skeincpu64.exe
taskkill /f /im skeincpu32.exe
taskkill /f /im skeingpu.exe
taskkill /f /im groestlcpu64.exe
taskkill /f /im groestlcpu32.exe
taskkill /f /im groestlgpu.exe
taskkill /f /im groestlnvgpu.exe
taskkill /f /im amdcpu64.exe
taskkill /f /im qubitcpu64.exe
taskkill /f /im qubitcpu32.exe
taskkill /f /im nvgpu.exe
taskkill /f /im qubitgpu.exe
